### ISSUE TITLE
Frequency And Thermal

### ISSUE THREAD

**Issue by adrianardizza** [zwliew/android_device_xiaomi_hm2014811#102]
The frequency is stuck at 1.2ghz, sometimes the phone heats up pretty quickly (about 55-60 when streaming videos), but battery consumption is adequate for normal usage

**Comment by adrianardizza** [comment]
Will continue to test heat while gaming, browsing, etc

**Comment by zwliew** [comment]
The freq gets stuck at 1.2 GHz for the first few min after boot as far as I have seen. Is that your problem?

55-60 degrees Celsius on what? CPU?

**Comment by adrianardizza** [comment]
Nvm, I think an app that I installed was causing it to heat, and the CPU isn't stuck after a bit
