### ISSUE TITLE
Call screen black

### ISSUE THREAD

**Issue by watson96** [zwliew/android_device_xiaomi_hm2014811#108]
The screen goes blank on my redmi 2(hm2014818 Indian variant of global) on outgoing calls and does not wake until call ends. I'm running the 26/09 build. Pls find fix it's a bit annoying! Otherwise the rest of the ROM is first class! Super smooth ROM. Keep up the good work!

**Comment by yogeshnet** [comment]
I'm having same problem with my red mi 2prime please help

**Comment by ankkitnegi** [comment]
Zwiliew is now not contributing anytime and he is not working on this model

**Comment by yogeshnet** [comment]
its working 
i hadn't done anything but suddenly its working now my screen does not turns black  during calls
