### ISSUE TITLE
Chrome doesn't show number of open tab, hence can't switch between multiple tabs

### ISSUE THREAD

**Issue by akashiyu** [zwliew/android_device_xiaomi_hm2014811#110]
Hi I am on 26/9 build, I installed chrome from play store and realized that square showing number of open tab is missing. Any idea why ?

**Comment by zwliew** [comment]
Do you have merged tabs and apps enabled in chrome?

**Comment by akashiyu** [comment]
Sorry had no idea about such option in chrome. Is it only enabled in lollipop by default ?
