### ISSUE TITLE
make system partitions to 1.5 gb

### ISSUE THREAD

**Issue by NeoDarkness** [zwliew/android_device_xiaomi_hm2014811#116]
I have problem to install stock gapps cause system memory is full

**Comment by charirma** [comment]
This looks a bit difficult to change it, I thought it better to be 1gb only, so users can get 5.5GB for install another application, but you can install pico version from this site: opengapps.org

**Comment by VIZ-KILLER** [comment]
You can use modular mini gapps

**Comment by nick37332001** [comment]
@charirma try open gapps nano
http://opengapps.org/
