### ISSUE TITLE
26/09 CM12.1: Black screen during call

### ISSUE THREAD

**Issue by teachmeluv** [zwliew/android_device_xiaomi_hm2014811#118]
As some other users have reported in the xda thread the screen goes black during a call. It's not a fault from the proximity sensor as sensor tester has confirmed it's working. 
If you have headphones connected during a call the screen stays on. 
Most user own a Redmi 2 Prime (013 and 018).
Please have a look into that.

**Comment by ankitdb11** [comment]
redmi 2 prime had no such issue. wat i think is dat this is a memory management issue mostly occuring with 1gb model when a user picks d call while he is doing more than moderate multitasking.

**Comment by teachmeluv** [comment]
I have Redmi 2 Prime and I got that issue so "it has that issue". Even a con-argument are the 2GB Ram I have so your comment makes no sense to me.

**Comment by ankitdb11** [comment]
model: 013 or 018??

**Comment by santosg23041993** [comment]
Then what to do??

**Comment by watson96** [comment]
Lol so this issue hasn't been closed? What happened to ROM dev-zwliew?

**Comment by zwliew** [comment]
Duplicate of 95. This only happens on a few devices.

**Comment by Nipun2212** [comment]
I am also facing the same problem of screen going blank during call...please help....
