### ISSUE TITLE
Android is Starting... starting apps

### ISSUE THREAD

**Issue by charirma** [zwliew/android_device_xiaomi_hm2014811#125]
it only took 5 seconds after turn on my phone, it is normal?
![p_20151007_140718](https://cloud.githubusercontent.com/assets/14859339/10332256/40d3645a-6d06-11e5-8bc1-285f7be8cbee.jpg)

![screenshot_2015-10-07-14-24-22](https://cloud.githubusercontent.com/assets/14859339/10332282/6a6d2c6a-6d06-11e5-825d-133c28974d1f.png)

**Comment by balika011** [comment]
Did you wipe before install?

**Comment by charirma** [comment]
yes, wiped cache, dalvik cache, data, but this is rarely happen. it happen 2 times in 4 days

**Comment by zwliew** [comment]
Nothing wrong.

**Comment by charirma** [comment]
but my phone run properly, just curious what caused it to happen? :)

**Comment by zwliew** [comment]
I think it happens when you wipe cache and/or dalvik cache.

**Comment by charirma** [comment]
I always delete the cache from the settings-storage before turn off the phone and I also use SD Maid app to clean up the junk files, it is causes the problem?

**Comment by zwliew** [comment]
Probably. It isn't even a problem actually. But I don't see any reason why you would want to remove cache, it serves a purpose.
