### ISSUE TITLE
FM is broken

### ISSUE THREAD

**Issue by zwliew** [zwliew/android_device_xiaomi_hm2014811#2]

**Comment by zwliew** [comment]
I think the root issue is related to SoundCloud being broken too.

**Comment by Silentlys** [comment]
cm12.1 branch display-caf and media-caf you are not open source

**Comment by zwliew** [comment]
Sorry, mind explaining what you meant by what?

**Comment by zwliew** [comment]
You can type in Chinese if you want, I'm Chinese too.

**Comment by Silentlys** [comment]
Media-caf 和display-caf 你用的哪个 cm 的貌似用不了

**Comment by zwliew** [comment]
为何用不了？

**Comment by zwliew** [comment]
你是说CM11或CM12呢？在CM11里，我没用使用Media-caf.

**Comment by Silentlys** [comment]
12.1

**Comment by Silentlys** [comment]
能加个qq吗 我也在优化这个机器的cm12.1

**Comment by Silentlys** [comment]
我的qq是1724962375

**Comment by Silentlys** [comment]
验证panyoujie

**Comment by zwliew** [comment]
对不起，我没用QQ。

**Comment by Silentlys** [comment]
你的device 双卡怎么解决的 貌似不管用啊

**Comment by zwliew** [comment]
对不起，我的QQ出了问题，现在我无法使用QQ。我没试过电话的双卡功能，因为我没有两个卡。

**Comment by zwliew** [comment]
请问你正在用哪个display HAL?或是用prebuilt的libraries?

**Comment by Silentlys** [comment]
我开源了其代码 media-caf 和display-caf

**Comment by zwliew** [comment]
Fixed.

**Comment by balika011** [comment]
wtf?!

**Comment by zwliew** [comment]
What's the matter? Sorry if you're confused, but the discussion above wasn't related to the FM issue, it was just a discussion on CM 12.1.

**Comment by balika011** [comment]
Oh it works well based on this tree. I'm using it on my phone.
