### ISSUE TITLE
Cell standby drain

### ISSUE THREAD

**Issue by mr201** [zwliew/android_device_xiaomi_hm2014811#22]
![screenshot_2015-07-11-04-30-42](https://cloud.githubusercontent.com/assets/13280167/8628481/f8bdf47a-2785-11e5-8781-884affdb0d2d.png)

Full signal, 2 min screen on time, the rest is cell standby.

**Comment by mr201** [comment]
![screenshot_2015-07-11-10-50-14](https://cloud.githubusercontent.com/assets/13280167/8632023/315d8702-27bb-11e5-877e-6e308485a8d5.png)

**Comment by zwliew** [comment]
What is your network provider?

**Comment by mr201** [comment]
Celcom(Malaysia), had full reception all the time & mobile data on LTE all day.

**Comment by balika011** [comment]
LTE can be the problem. Can you try to change force 3G?

**Comment by zwliew** [comment]
When did this issue start happening?

**Comment by mr201** [comment]
since your early build. mostly if i rarely use the screen since full charge. even with mobile data off.

**Comment by zwliew** [comment]
since the first build ever? I don't really know what I can do about this, since this seem to be unique to you.

**Comment by mr201** [comment]
Guess so as no one else troubled by this problem.   My model is hm2014817 and the default rom doesnt have this problem except other non miui rom & custom miui roms. Consider this issue solved. Thanks
