### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by devilgoldy** [zwliew/android_device_xiaomi_hm2014811#23]
(restricted access Change )disable the this notification

**Comment by zwliew** [comment]
what?

**Comment by devilgoldy** [comment]
www.thunderzap.in/cyanogenmod-11-beta-4-for-android-one-fixes-data-and-3g-on-sim2-paves-way-for-official-support/

read this

**Comment by zwliew** [comment]
When does the notification appear for you?

**Comment by devilgoldy** [comment]
any time on network changing

**Comment by zwliew** [comment]
As in? Changing from 2G to 4G? Never appears for me.

**Comment by devilgoldy** [comment]
but changing 2g to 3g it appey

**Comment by zwliew** [comment]
Never appears.
