### ISSUE TITLE
WIFI SIM Based Connection

### ISSUE THREAD

**Issue by nick37332001** [zwliew/android_device_xiaomi_hm2014811#27]
Please add this feature... It is useful for connecting to Wireless@SGX

**Comment by nick37332001** [comment]
![screenshot_2015-07-11-22-48-51 1](https://cloud.githubusercontent.com/assets/6513413/8888259/a431c216-32d8-11e5-8fbe-892e6c7100a8.png)
http://www.ida.gov.sg/Tech-Scene-News/Infrastructure/Wireless/Wireless-at-SG/For-Consumer/SIM-based-Connection-Guide

It's an EAP method of connecting... Reply please?

**Comment by zwliew** [comment]
Doesn't seem to be supported in AOSP 4.4.4 or CM 11 for that matter. Use Wireless@SG instead, I guess?

**Comment by nick37332001** [comment]
It seams to be supported in samsung's touch wiz and miui... so apparently it is possible to add that feature...

**Comment by zwliew** [comment]
It is added by OEMs, but not present in AOSP KitKat nor CM 11.

**Comment by nick37332001** [comment]
https://android-review.googlesource.com/#/c/71113/
Can you implement it then?

**Comment by zwliew** [comment]
No, I won't add code not already in CM 11. Besides, it requires more patches than just that.
