### ISSUE TITLE
network

### ISSUE THREAD

**Issue by devilgoldy** [zwliew/android_device_xiaomi_hm2014811#28]
network gone when using data and after some time network are normal 2g to 3g network changing speed also slow

**Comment by zwliew** [comment]
Normal.

**Comment by devilgoldy** [comment]
not normal other cm 11 are faster network changing speed and no network drop

**Comment by devilgoldy** [comment]
please fix the network issues

**Comment by mr201** [comment]
I think he meant 2g only & 3g only network mode, just realised you didnt include it

**Comment by zwliew** [comment]
Network is working fine for me. He definitely doesn't mean 2g/3g only modes, and I won't add them even if he did mean that.
