### ISSUE TITLE
Kernel compatibility with 2014813

### ISSUE THREAD

**Issue by thePanz** [zwliew/android_device_xiaomi_hm2014811#30]
This issue is just to clarify if this kernel is compatible with 2014813 (or other 201481x variants) devices.
If not, can you grade the effort to 'port' the kernel to such devices?
Thank you in advance for your answer, and keep the good job you're doing here!

**Comment by zwliew** [comment]
Should be compatible with all redmi 2 variants.

**Comment by zwliew** [comment]
This kernel isn't used in the device, it is just used in build time for header file references.
