### ISSUE TITLE
How build?

### ISSUE THREAD

**Issue by amspeople** [zwliew/android_device_xiaomi_hm2014811#32]
Try:
. build/envsetup.sh
breakfast hm2014811
mka bacon

Result: make: *** Нет правила для сборки цели `/home/amsuser/android/cm12.1/out/target/product/hm2014811/obj/KERNEL_OBJ/usr', требуемой для `/home/amsuser/android/cm12.1/out/target/product/hm2014811/obj/EXECUTABLES/adbd_intermediates/adb.o'.  Останов.

**Comment by zwliew** [comment]
Cm 12.1 branch doesn't work.

**Comment by amspeople** [comment]
The vendor repository is already there. Made it with scripts. But here's where to get the kernel repository?

**Comment by zwliew** [comment]
they are all on my github

**Comment by amspeople** [comment]
Haha) I'm Sorry, completely blind)
