### ISSUE TITLE
wakeup

### ISSUE THREAD

**Issue by devilgoldy** [zwliew/android_device_xiaomi_hm2014811#34]
why you not add option for wake with volume buttons

**Comment by zwliew** [comment]
Currently, I don't feel like enabling that feature as I don't feel that volume buttons should be allowed/used to wake up a device.

**Comment by zwliew** [comment]
Since you want it so much, https://github.com/zwliew/android_device_xiaomi_hm2014811/commit/090c1936ae1affa60cfb8ffdf2da62cc2beab091.

Happy now?
