### ISSUE TITLE
Gps

### ISSUE THREAD

**Issue by devilgoldy** [zwliew/android_device_xiaomi_hm2014811#35]
Can you tell me how to fix GPS can not detect any setlites in other ROM

**Comment by zwliew** [comment]
Is there a problem with GPS in this ROM?

**Comment by devilgoldy** [comment]
in your ROM GPS works great  but carbon ROM GPS not detect any setlites if I replace gps.so file  GPS work or not

**Comment by zwliew** [comment]
Can't help you with that sorry, it depends a lot on what the ROM provider did.
