### ISSUE TITLE
MTP and USB Mass Storage broken

### ISSUE THREAD

**Issue by Cu2OH2CO3** [zwliew/android_device_xiaomi_hm2014811#40]
When I turn on MTP, my computer plays the "Device plugged" sound with a following "Unplugged" sound. Nothing appears in This Computer, neither in Device Management. ADB is also broken in MTP mode, showing an "error: device not found". My phone is waken up periodically for unknown reasons.
When I turn on UMS, the Device Management shows an "Unknown USB device". After I installed the general disk driver manually, a new disk appeared "Uninitialized" in Disk Management. ADB works in UMS mode however.
PTP works fine.

**Comment by Cu2OH2CO3** [comment]
MTP seems to be working in Ubuntu, but I need to use Windows most of the time ... I'm using Windows 8.1 64 bit

**Comment by zwliew** [comment]
Does your Windows have the appropriate driver support? MTP works fine for me.

**Comment by xonders** [comment]
Have the same problem. I can connect to PC (Windows 8.1 x64) only when switch off usb debug in developers settings.

**Comment by Cu2OH2CO3** [comment]
Well, on stock MIUI, MTP works fine. Maybe that's because I'm using the China Mobile variant of Redmi 2?

**Comment by xonders** [comment]
On stock MIUI no so problems too. Im using 2014811.

**Comment by balika011** [comment]
Note 4G has the same weird bug. We dunno the reason.

**Comment by zwliew** [comment]
Did it not work since the first build?

**Comment by Cu2OH2CO3** [comment]
Seems to be a problem with kernel and/or ramdisk ... I flashed boot image from 20150614 and both MTP and ADB worked fine. (UMS still broken although I know that neither MIUI provides this functionality)
BTW there's a bug in adbd which produces bogus output when launching ADB shell on Windows and there's no such bug in MIUI

**Comment by zwliew** [comment]
Can you try 13/07/2015?

**Comment by Cu2OH2CO3** [comment]
MTP is OK in 20150713.

**Comment by nick37332001** [comment]
That happens to me too sometimes but one time it was really bad... Windows keep playing connect and disconnect sound repeatedly.

**Comment by zwliew** [comment]
ADB and MTP is working fine on the latest build in Windows for my device.

**Comment by zwliew** [comment]
Closed due to inactivity.
