### ISSUE TITLE
Compass work but wrong direction

### ISSUE THREAD

**Issue by rizmajofe27** [zwliew/android_device_xiaomi_hm2014811#42]
Hi, I'm using ur CM11 but why the compass give me wrong direction, already calibrated it by moving like 8 Shape but it still give me wrong direction

**Comment by zwliew** [comment]
Compass working exactly like in stock MIUI here.

**Comment by rizmajofe27** [comment]
Maybe i need to recalibrate it again

**Comment by rizmajofe27** [comment]
Btw , i've recalibrated it many times but it still gave me wrong direction, when i face east the compass show it's north , when i face west the compass show that it's south

**Comment by kb0n** [comment]
Just a shot in the dark: Maybe it's somehow related to screen-rotation and some misinterpreted values?

**Comment by zwliew** [comment]
Did it work on precious builds? Like the build before the latest.
