### ISSUE TITLE
Build 25/07 issues

### ISSUE THREAD

**Issue by rameshonline** [zwliew/android_device_xiaomi_hm2014811#47]
I am seeing the following issues -

1) Notification light is still displayed during calls and SMS even though disabled in Settings.
2) USB is getting detected rarely. MTP is not getting detected.

**Comment by zwliew** [comment]
MTP gets detected 100% of the time. Change your USB port or your cable, it could be spoilt.

**Comment by zwliew** [comment]
You must have done something wrongly, notification light isn't displayed when disabled, even for calls and SMS.
