### ISSUE TITLE
Proximity bug

### ISSUE THREAD

**Issue by ssawrav** [zwliew/android_device_xiaomi_hm2014811#5]
In my phone(Device ID:201418),there's a proximity sensor problem during call,the display doesn't turn on until the call disconnects.

**Comment by balika011** [comment]
Its a kernel bug. I'll fix it whit a custom kernel. WIP. ATM. we are using xiaomi's prebuilt one.

**Comment by ZuBB** [comment]
But in stock MIUI (which uses xiaomi's prebuilt kernel I guess) we do not have that bug..
How it is possible that same kernel image at same time causes proximity work on ROM "BAR" and do not work on ROM "BAZ"?

I am not guru in whole android space, but to me this looks weird..

at 4pda.ru (russian forum for mobile devices) someone told that for FIUI Beta 2.8.0 ROM (based on cm11 also) proximity works ok for our device(s)

there is an app proximitiscreenoff-lite which promises to solve issues like that. it does not help either. however it has built in tests for proximity sensor. For some reason after call is ended and phone is moved back to our eyes value of that sensor does not changes back to '5'. fro my cases I need to rotate a phone till 0 was replaces by 5. not sure if this may help to you, but still

@zwliew, @balika011 do you have any when this issue may be fixed?

Thanks for you amazing work

**Comment by zwliew** [comment]
The thing is, compass works fine for some and doesn't work for others.

Im wondering whether it is possible for different devices have different compass sensors? From what I know, our compass sensor is by AKM (AKM0911?), but I wonder if people whose compasssensors don't work have a different sensor.

**Comment by ZuBB** [comment]
How to know which sensor is my phone? (btw I own *13 model but after installing your build in status page everywhere *11 is listed)

**Comment by ZuBB** [comment]
Can this app help us? https://play.google.com/store/apps/details?id=zausan.zdevicetest&hl=en

**Comment by ZuBB** [comment]
I have found one more app that detects a proximity sensor chip vendor and both of them says for my phone its **liteon**.

**Comment by ZuBB** [comment]
http://specdevice.com/showspec.php?id=f8de-0df6-794a-18b91c105cee

**Comment by ZuBB** [comment]
btw for all redmi 2 variants in specdevice.com db vendor of proximity sensor is liteon

**Comment by zwliew** [comment]
Oops why did I talk about compass lol. This is what I get for thinking about side projects halfway through lessons.

**Comment by ZuBB** [comment]
I would like to see that thinking does not disappear too early ;)

Please collaborate with balika011 and make you best to get this fixed. currently this is major issue while using this phone

**Comment by ZuBB** [comment]
Should proximity issue disappear with newest build?

**Comment by zwliew** [comment]
No, I just have no idea how to fix this.

**Comment by ZuBB** [comment]
ok. than I guess we need to keep this issue opened. just as a reminder

**Comment by zwliew** [comment]
This is impossible to fix at this point. Unless I have sufficient data or info on what makes a "bugged" device different from one that has a working proximity, I have no way of debugging this.

**Comment by kb0n** [comment]
So it's because of lack of data, not because it wil definetly never be fixed. Isn't that exactly why it would be good practice to leave the bug report open?! ;)
I guarantee you, the next user with this problems cheks the open issues, sees "there's no open report on proximity problem" and will create a new ticket on this.

**Comment by nhocbaby76** [comment]
In my devices,Compass is yas537-mag by Yamaha.I think some devices use AKM and some devices use Yamaha

**Comment by nhocbaby76** [comment]
In may devices,70% cook rom can't use proximity sensor like Flyme OS CM11 Crdroid.I can use proximity in ColorOS 2.0.1 port from oppo mirror 3 and FIUI 2.8.0

**Comment by zwliew** [comment]
We're talking about proximity sensor, not compass unfortunately. Compass is working perfectly fine. I believe proximity only has 1 variant which is manufactured by liteon.

**Comment by nhocbaby76** [comment]
yes my devices is manufactured by liteon but i didn't know why my friend can use proximity in cook rom and i can't

**Comment by zwliew** [comment]
Can you contact me via Hangouts? I woud like you to test a build with an experimental proximity fix.

**Comment by zwliew** [comment]
https://plus.google.com/+ZhaoWeiLiew

**Comment by nhocbaby76** [comment]
ok.i just send you a message in hangouts

**Comment by zwliew** [comment]
Fixed.

**Comment by ZuBB** [comment]
On Tuesday managed to install build with fix for this issue. Would like to confirm that no w proximity sensor works really good!

Thanks a lot to @zwliew and everybody who helped to solve it
