### ISSUE TITLE
Full battery led

### ISSUE THREAD

**Issue by nick37332001** [zwliew/android_device_xiaomi_hm2014811#50]
The green notification LED stays green until it drops 1% from fully charge even when device is unplugged.

**Comment by emfox** [comment]
I confirm this bug, by recharge the battery to full, and unplug the recharger, if no other event trigger the led, it keeps green all the time, even when turn off the screen.

**Comment by nick37332001** [comment]
There should be an event which checks if cable is unplugged...

**Comment by flame-qa** [comment]
Guys, its not bug - its a feature

**Comment by nick37332001** [comment]
@flame-qa It is a bug... Usually after full charge, battery light stays green until it is unplugged from charger but that is not the case here.
