### ISSUE TITLE
2G/3G toggle in quick settings not working

### ISSUE THREAD

**Issue by pablosee** [zwliew/android_device_xiaomi_hm2014811#52]
2G/3G toggle in quick settings not working. After pressing button i quick settings nothing happens. Only after long press jumps to network settings and 2G/3G/LTE can bet set.

**Comment by zwliew** [comment]
There is a 2G/3G toggle in quick settings?

**Comment by pablosee** [comment]
system settings, nofitifaction drawer, quick settings panel, tiles and layout, ADD (plus sign), add "network mode".
But strangely I have network mode tile, but it's gone from toggles list. Hmm... I whose there, but now it's gone.

**Comment by zwliew** [comment]
It was never there for me, did you use an Xposed module or a mod to add it in?

**Comment by Cu2OH2CO3** [comment]
There is surely a "Network mode" tile in CM11. You can manually add it to the quick settings. Its source can be found in frameworks/base/packages/SystemUI/src/com/android/systemui/quicksettings/MobileNetworkTypeTile.java [Branch cm-11.0]
