### ISSUE TITLE
incoming calls not ringing on xiaomi redmi 2 and also sound recorder not working properly

### ISSUE THREAD

**Issue by dharmesh250877** [zwliew/android_device_xiaomi_hm2014811#53]

**Comment by dharmesh250877** [comment]
Pl help to resolve below issues
model no xiaomi redmi 2 2014811

No ringing during incoming calls
sound recorder not working
Camera quality not good

**Comment by dharmesh250877** [comment]
pl help urgently and support to experience such a beautifullly designed rom

**Comment by zwliew** [comment]
Phone rings perfectly fine. Can't do much about sound recorder quality and camera quality. May mess with audio routes in the future.
