### ISSUE TITLE
Update to 5.7.16 kernel

### ISSUE THREAD

**Issue by nick37332001** [zwliew/android_device_xiaomi_hm2014811#54]
there is a new kernel...

**Comment by zwliew** [comment]
I'm not on Ubuntu anymore as I've just rewiped my whole machine with Windows 10. It will take a while more before I work on the project again. As for the kernel, I highly doubt there is any change compared to 5.7.2

**Comment by balika011** [comment]
would you like to use my kernel source?

**Comment by zwliew** [comment]
Sure, but the somehow the zip file you sent me previously didn't boot for me.
