### ISSUE TITLE
Z ram

### ISSUE THREAD

**Issue by devilgoldy** [zwliew/android_device_xiaomi_hm2014811#59]
able the z ram

**Comment by zwliew** [comment]
Dude zram is already enabled in the latest build, can you please stop creating useless and meaningless issues?

**Comment by zwliew** [comment]
Okay, maybe I've made a mistake. Is it not enabled in the latest build? If you want, just enable it using in Kernel Adiutor.

Stop creating useless, duplicate threads that just annoy the heck out of me.
