### ISSUE TITLE
Auto-rotate freeze and crash in apps

### ISSUE THREAD

**Issue by Crowman1** [zwliew/android_device_xiaomi_hm2014811#64]
Auto-rotate freezes when used in apps, e.g. PDF readers, emulators, etc.
Tested on 20150802 version, will try with 20150725.
Freeze occurs immediately, after few seconds screen turns black and phone is no longer responding to input.

**Comment by zwliew** [comment]
Is this similar to https://github.com/zwliew/android_device_xiaomi_hm2014811/issues/67?

**Comment by Crowman1** [comment]
I think it might not be related. Or rather, the conditions that lead to problem are not the same.
I have very consistent behavior. Whenever I browse the internet or use any kind of app intergrated in the build it's ok. I have few applications(2 pdf readers, one emulator), that do this consistently, whenever I want to rotate it, whole phone freezes. When I do not rotate the app,app works fine.
It seems to me apps might use some funcion that directly leads to freeze.
I'll post logs if i can trace it to something.

**Comment by zwliew** [comment]
Some logs would be good. Also please tell me what app does this.
