### ISSUE TITLE
black screen while calling

### ISSUE THREAD

**Issue by ThomasMidgley** [zwliew/android_device_xiaomi_hm2014811#65]
screens turns black when making a phone call (even when the phone is laying down). Screen does not wake up anymore, so there is no possibility to end a call from my side. screen does not wake up when pressing the power button.
Once the other caller ends the phone call the screen comes back

**Comment by balika011** [comment]
Proximity bug.
Build?

**Comment by ThomasMidgley** [comment]
i see
cm_hm2014811-userdebug 4.4.4 KTU84Q

**Comment by balika011** [comment]
Then can you close it pls?

**Comment by ThomasMidgley** [comment]
solved
