### ISSUE TITLE
compass has wrong direction rotation

### ISSUE THREAD

**Issue by AlexABu** [zwliew/android_device_xiaomi_hm2014811#66]
cm-11-20150802-UNOFFICIAL-hm2014811

I've been trying to calibrate compass with many programs (AndroiTS GPS, GPS status, SunSurveyor), but every time it points North, but rotates wrong: when I rotate phone right 45 geg, compass rotates 90 deg RIGHT TOO.

**Comment by teachmeluv** [comment]
Hi,

please use this App "GPS Essentials" from Playstore to calibrate your compass. You are even free to use the App "GPS Status" (also from Playstore) to reset your GPS Data and download new ones. Worked on this ROM very nice for me.

**Comment by AlexABu** [comment]
Any software, including "GPS Essentials", gives wrong result. Has anybody more ideas?

**Comment by zwliew** [comment]
Fixed in CM 12.1
