### ISSUE TITLE
Random black screen/freeze

### ISSUE THREAD

**Issue by SolykZ** [zwliew/android_device_xiaomi_hm2014811#67]
Hello there,

First of all, I'd like to thank you for this usable ROM. MIUI was such a pain in the b*tt... 

I flashed the August 2nd ROM earlier this week. Everything works fine except that sometimes, the screen goes full black and the phone won't respond anymore. I have to reboot it to get it working again. Sometimes it's when I'm on Facebook, sometimes when I'm in the settings app. Sometimes on the Play Store... That seems very random. 

Also, I tried to figure out what was wrong by myself by installing logs-reading apps, with no luck: the logs seems to get wiped after each reboot. However, if you tell me how to get you some logs, I'd love to help you to figure out what's wrong.

Regards,
Chris.

**Comment by kb0n** [comment]
So if you can reboot it, it means it DOES respond!?
It also means that you should be able to connect your phone and use `adb logcat`. If you can anticipate that problem, you can `adb logcat` prior to it and live track what's happening until the screen turns black (of course copy&paste that afterwards for report ;) )

Before rebooting, you should be able to store the kernel output as well (e.g. into a local *dmesg.txt* file):
```
adb shell dmesg > dmesg.txt
```

If that doesn't work out and you **have** to reboot, get the last kernel output (e.g. into a local *kmesg.txt* file):
```
adb cat /proc/last_kmsg > kmesg.txt
```

**Comment by SolykZ** [comment]
Hello kb0n,

The phone only responds to a hard reset (long press on the power button) and when I plug in on a computer I can access my files.

I enabled USB Debug and ADB Root in the developper options. Now I'll just wait to my phone crash.

However, I have you to know that the command "adb shell cat /proc/last_kmsg" returns "/system/bin/sh: cat: /proc/last_kmsg: No such file or directory". Maybe that's because the developper options were not enabled before the current boot? Idk.

Thanks for you help, anyway. ;-)

**Comment by SolykZ** [comment]
Me again,

So my phone just crashed. I immediately plugged it on my computer and fired an adb devices to start a daemon. No luck here, my phone wasn't recognized by the command. It was visible in the Windows device manager, however.

So I hard reset it to see if some /proc/last_kmsg file was dumpable, nothing there, like I said in my previous post.

This time I was just reading some posts on Facebook.

If you have another idea...

**Comment by SolykZ** [comment]
Hello,

I finally had a crash while redirecting dmsg to a file. Now, what should I search for in the logs? I don't see much things related to a crash in the EOF, except lines talking about freeing memory.

This time I was on Google Play while some apps were updating when the phone crashed.

Regards,
Chris.

**Comment by OLDsheep** [comment]
I confirm it in the 29/8 build.

**Comment by VIZ-KILLER** [comment]
i too confirm it in 29/8th build

**Comment by zwliew** [comment]
Try disabling KSM.

echo 0 > /sys/kernel/mm/ksm/run

**Comment by zwliew** [comment]
This should be greatly reduced in the next CM 12.1 build.

**Comment by SolykZ** [comment]
Nice to hear that for CM 12. But what about CM 11? I don't know if the Redmi 2 is powerful enough for Lollipop, so for now I'll keep Kitkat.

**Comment by zwliew** [comment]
Redmi 2 is definitely powerful enough for Lollipop. In fact, it is much smoother on Lollipop due to performance optimizations.

**Comment by SolykZ** [comment]
In my opinion, when you say "Note: these can't be fully removed, they are caused by direct reclaim running due to lack of memory, especially when launching a memory-intensive app or task" about black screen and freezes issues, that's a clue about the ability for the Redmi 2 to correctly manage Lollipop. Or Kitkat, since these bugs are present on it too.

**Comment by zwliew** [comment]
Nope, it happens on every 1GB RAM device. It is just a matter of lack of RAM.

**Comment by SolykZ** [comment]
I've got here a Wiko Birdy with just 1 GB RAM and it just works. I gave it to my wife because I needed a dualSIM phone for my work but I was very happy with it. No lags nor freezes. Just perfect. And only 1 GB RAM. No, actually I'm sure that there's something wrong with this ROM. A phone have to *not* freeze with just Facebook opened.

**Comment by zwliew** [comment]
The ROM doesn't freeze with just Facebook opened. I use Facebook daily.

**Comment by SolykZ** [comment]
Go read again my first message. As I already said, it does. I'm notre willing to give more time to this thread if you just come here to pretend that the bug reports are fake.

If you're not able to give correct support to something you dev, just don't dev. Let serious people do it.

Regards,
Chris.

**Comment by zwliew** [comment]
I have never pretended that the bug reports are fake. However, I can hardly care (to give more time out of my life to this thread) if absolutely 0 logcats or dmesgs were given.

Thus, I can't even be sure if it is due to direct reclaim occurring when a memory intensive app/process is started while existing free memory is low. Even if it is, I have already said that I have been tuning parameters to make such direct reclaims less noticeable.

I can't be bothered to release a new build for CM 11.0 because I only have a laptop with 250 GB of storage, dual booting Windows and Ubuntu. It is much too tiresome to have to sync a new repo and waste more time of my life on a problem (that I don't even know the cause of).
