### ISSUE TITLE
Notification light does not work

### ISSUE THREAD

**Issue by OLDsheep** [zwliew/android_device_xiaomi_hm2014811#71]
The notification light does not work, except when charging the device.

**Comment by pablosee** [comment]
I can confirm that.

**Comment by zwliew** [comment]
Fixed in September 5 release.

**Comment by OLDsheep** [comment]
in cm11

**Comment by zwliew** [comment]
It doesn't? It worked for me.

**Comment by OLDsheep** [comment]
only in the 2/8 build

**Comment by OLDsheep** [comment]
Check this rom, it has no bugs: http://en.miui.com/thread-111502-1-1.html

**Comment by zwliew** [comment]
Well revert to 2/8 build I guess. 2/8 build is more stable since 29/8 was just a stepping stone for integration with the open sourced kernel. I may or may not release a new CM 11.0 build to fix the existing bugs.
