### ISSUE TITLE
Kernel wakelock i2c 0-023

### ISSUE THREAD

**Issue by pablosee** [zwliew/android_device_xiaomi_hm2014811#72]
88% kernel wakelock from 0-023 (i2c GPIO?) Deep sleep only 12%
Can provide logcat, dmesg and BBS log

**Comment by zwliew** [comment]
Provide BBS log please.

**Comment by zwliew** [comment]
Closing since there is no news.

**Comment by mdpuma** [comment]
Hi,

I have same issue with CM 11.0 20150829. I send dmesg and logcat to zhaoweiliew@gmail.com.
