### ISSUE TITLE
No camera app 

### ISSUE THREAD

**Issue by VIZ-KILLER** [zwliew/android_device_xiaomi_hm2014811#79]
All camera apps shows ''can't connect to camera'' error message.

**Comment by veerendra-nath** [comment]
camera was fixes by kumajaya
take that blobs

**Comment by zwliew** [comment]
Fixed in the next build.

**Comment by VIZ-KILLER** [comment]
When will the next file be uploaded? Waiting for ur build

**Comment by zwliew** [comment]
Today.

**Comment by VIZ-KILLER** [comment]
Thank  you for the reply I see lot of commits today

**Comment by VIZ-KILLER** [comment]
U used  open source camera Hals? It was working on kumajayas builds.

**Comment by zwliew** [comment]
Check the new build out on my XDA thread.

**Comment by VIZ-KILLER** [comment]
Downloading

**Comment by ashokvishnoi1994** [comment]
Hey I am running kumajaya's latest build. I want to test yours too. Can I flash it without formatting data and apps?

**Comment by zwliew** [comment]
You can try, I don't think there will be problems but I can't be sure.

**Comment by ashokvishnoi1994** [comment]
Okay.

**Comment by ashokvishnoi1994** [comment]
After I installed without formatting apps and data, everything is working fine except camera stopped working so I guess I will have to freah reinstall.

**Comment by zwliew** [comment]
There is something wrong with camera in the latest build.

**Comment by adrianardizza** [comment]
Sorry for the late response, as i said before, after the first reboot the camera basically decides to not work suddenly, heres the log when i tried to open the camera app AFTER the reboot:
---- Sep 25, 2015 9:41:55 PM ----

09-25 21:41:56.742  3606  3606 I Timeline: Timeline: Activity_launch_request id:com.android.camera2 time:414381

09-25 21:41:56.743   692  2940 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.camera2/com.android.camera.CameraLauncher bnds=[571,1131][705,1291] (has extras)} from uid 10018 on display 0

09-25 21:41:56.808   692  3626 I ActivityManager: Start proc 7706:com.android.camera2/u0a33 for activity com.android.camera2/com.android.camera.CameraLauncher

09-25 21:42:07.037  7706  7706 E AndroidRuntime: Process: com.android.camera2, PID: 7706

09-25 21:42:07.037  7706  7706 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.camera2/com.android.camera.CameraActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.camera.util.PhotoSphereHelper$PanoramaViewHelper.onStart()' on a null object reference

09-25 21:42:07.038   692   708 W ActivityManager:   Force finishing activity 1 com.android.camera2/com.android.camera.CameraLauncher

09-25 21:42:07.346   692   708 I WindowManager: Screenshot max retries 4 of Token{31bb7777 ActivityRecord{29170576 u0 com.android.camera2/com.android.camera.CameraLauncher t36 f}} appWin=Window{1e13de6f u0 Starting com.android.camera2} drawState=4

09-25 21:42:07.848   692   949 W ActivityManager: Activity pause timeout for ActivityRecord{29170576 u0 com.android.camera2/com.android.camera.CameraLauncher t36 f}

09-25 21:42:08.855  3044  3044 W PackageManager: Failure retrieving resources for com.android.camera2: Resource ID #0x0

09-25 21:42:09.456   692  3511 I WindowState: WIN DEATH: Window{32f02380 u0 com.android.camera2/com.android.camera.CameraLauncher}

09-25 21:42:09.456   692  3301 I ActivityManager: Process com.android.camera2 (pid 7706) has died

---- Sep 25, 2015 9:42:13 PM ----

**Comment by zwliew** [comment]
Refrain from using the latest build, use the previous build for now.

**Comment by adrianardizza** [comment]
ok, thanks for the clarification i guess, good luck and thanks for developing this even though Xiao** haven't released the kernel sources :3

**Comment by VIZ-KILLER** [comment]
There is no camera bug if we clean install the latest build . but of we flash it over kumajayas build(dirty  flash) the camera apps shows can't start camera error.

**Comment by zwliew** [comment]
Fixed, new build today.
