### ISSUE TITLE
Cm 11 wich must be fix

### ISSUE THREAD

**Issue by NeoDarkness** [zwliew/android_device_xiaomi_hm2014811#82]
1.logo linux in first boot
2.battrey status not accurate
3.light sensor in camera

Sorry bad english

**Comment by billy97** [comment]
Please fix this bug

**Comment by zwliew** [comment]
CM 11.0 is kind of dead now, I may release a build, but not soon. Use the previous build of CM 11.0 instead of the latest one to have none of the bugs.

**Comment by billy97** [comment]
Up !

**Comment by billy97** [comment]
When you release new build cm11 dude ?

**Comment by skyline75489** [comment]
@zwliew  Which of the old build doesn't have those bugs?

**Comment by zwliew** [comment]
The build using the prebuilt kernel doesn't have those bugs. If I remember correctly, it is the 2nd latest build.

**Comment by skyline75489** [comment]
I'm currently using the latest 8-29 build(Thanks for the amazing work, by the way). Should I flash the 2nd latest build? Is it worth it?

**Comment by zwliew** [comment]
Yeah, the latest build was mainly a test build to test a source built kernel

**Comment by skyline75489** [comment]
Thanks for pointing out this. I'll give it a try.
