### ISSUE TITLE
Wake up delay

### ISSUE THREAD

**Issue by VIZ-KILLER** [zwliew/android_device_xiaomi_hm2014811#86]
Screen takes some time to wake up after pressing the power button.

**Comment by VIZ-KILLER** [comment]
This problem is in cm 12.1

**Comment by zwliew** [comment]
How long is your screen-on delay? I remember reducing it from ~3s to ~600ms in the latest build.

**Comment by VIZ-KILLER** [comment]
It doesn't happen always!   
Donno what's the problem 
Waiting for your next build with camera fix

**Comment by VIZ-KILLER** [comment]
It was fixed in latest build
