### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by mueedqadri** [zwliew/android_device_xiaomi_hm2014811#87]
Screen keeps on going on and the goes black untill i touch it.

**Comment by zwliew** [comment]
Does it persist after a manual screen off and on?

I've reverted the problematic commit and it will be fixed in the next build.

**Comment by zwliew** [comment]
Sorry, can you try this boot image and tell me whether the problem persists? And the previous question: Does it persist after a manual screen off and on?

To install it: Use Flashify from the play store. Be sure to back up your current boot image before flashing it.

https://basketbuild.com/filedl/devs?dev=zwliew&dl=zwliew/hm2014811/boot.img

**Comment by zwliew** [comment]
Fixed in the next build.
