### ISSUE TITLE
KSM drains battery

### ISSUE THREAD

**Issue by mbbill** [zwliew/android_device_xiaomi_hm2014811#88]
Just taking a look at the kernel cpu usage in BBS(better battery status) the ksmd consumes a lot of cpu time in the background (like several hours of kernel time). Dig a little bit into /sys/kernel/mm/ksm/, the sleep_millisecs is set to 20 which means the ksmd will wake up every 20ms.
I would suggest turning off the kms entirely (set run to 0) or make it sleep a bit longer.

**Comment by zwliew** [comment]
Are you using CM 11.0 or CM 12.1 and which build? In both builds,

I have sleep_millisecs set to 500 ms and 100 ms respectively in init, so it should not be 20ms. I may have to take a look at this.

**Comment by mbbill** [comment]
Thanks for the quick reply!
I'm using "cm-12.1-20150917-UNOFFICIAL-hm2014811.zip"

**Comment by zwliew** [comment]
It is possible that the desired parameters for KSM were set too early and the KSM driver wasn't initialized before setting them. This will be fixed in the next build.

**Comment by zwliew** [comment]
Fixed in the next build.

**Comment by zwliew** [comment]
Please try out the new build to see whether it is still stuck on 20ms. I have set it to 500ms in init.

**Comment by VIZ-KILLER** [comment]
Is it uploaded?

**Comment by zwliew** [comment]
Soon.

**Comment by VIZ-KILLER** [comment]
I just saw the new build now not visible! What happened?

**Comment by mbbill** [comment]
tried the 0926 build, still 20ms.
