### ISSUE TITLE
64bits

### ISSUE THREAD

**Issue by OLDsheep** [zwliew/android_device_xiaomi_hm2014811#91]
Can you take a time of your day to explain or give a link about why is the cm12.1 running in 32bits?

**Comment by zwliew** [comment]
We need a compatible bootloader to load 64bit images.

**Comment by OLDsheep** [comment]
wow, you are fast.

so basically it's cause of the sources that xiaomi did not release?

**Comment by zwliew** [comment]
Xiaomi isn't obligated to release the source code of the bootloader if I remember correctly, it is that Xiaomi doesn't have a Lollipop release with 64-bit support.

**Comment by OLDsheep** [comment]
What about the new MIUI 7 build (lollipop) for the Mi Note Pro that is coming this friday? Do you think it can help since the Mi Note Pro has a 64bit cpu?
http://en.miui.com/thread-163630-1-1.html

**Comment by zwliew** [comment]
Nope, it has to be for Redmi 2 or at least a device similar to Redmi 2. I wouldn't sweat too much about it anyway since 64bit doesn't bring that much improvements to the table.

**Comment by OLDsheep** [comment]
Ok, thanks for the help.

**Comment by balika011** [comment]
I flashed bootloader form almost the same device. My Rm2 dead now. And its looks like not a signature error.

**Comment by zwliew** [comment]
I thought you managed to flash bootloader from a similar Lenovo (is it?) device?

**Comment by OLDsheep** [comment]
I bet on this device: https://wiki.cyanogenmod.org/w/Rendang_Info

**Comment by zwliew** [comment]
It is dangerous to flash bootloaders, as balika011 said. Furthermore, rendang isn't 64bit.

**Comment by OLDsheep** [comment]
Well, the only device I know that is 64bit is the Moto G3.

Good Luck solving it.

**Comment by balika011** [comment]
There are a lot of 64bit devices. For ex Mi 4i.
2015. szept. 25. 1:32 ezt írta ("Victor Dubas" <notifications@github.com>):

**Comment by OLDsheep** [comment]
Yes, but the G3 uses the same SoC.

**Comment by VIZ-KILLER** [comment]
YUPHORIA is 64 bit
