### ISSUE TITLE
Overclocking support

### ISSUE THREAD

**Issue by nick37332001** [zwliew/android_device_xiaomi_hm2014811#92]
Can you add over clocking support from this msm8916 kernel https://github.com/neobuddy89/yu_msm8916/commit/9384f73fcc40bc6f74362e1690694bdddff3ab1d of yu yuphoria? Since its the same cpu I am pretty sure it is possible

**Comment by zwliew** [comment]
No, sorry. Optimizations in framework is plenty for us.

**Comment by nick37332001** [comment]
What do you mean by that?

**Comment by zwliew** [comment]
We have plenty of optimizations in the framework that hook to the PowerHAL, boosting our CPU during vital moments like scrolling, opening apps, improving UX greatly. We don't need that 100 MHz or so more CPU frequency.

Furthermore, we already stay at relatively high CPU speeds most of the time, and unless your CPU is binned pretty well, you may suffer from excessive heat output.

**Comment by nick37332001** [comment]
Ok anyways next few days no school XD #haze

**Comment by zwliew** [comment]
:+1:
