### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by nick37332001** [zwliew/android_device_xiaomi_hm2014811#94]
http://pastebin.com/5f7Jcr9n
Is this common?

**Comment by zwliew** [comment]
What is?

**Comment by nick37332001** [comment]
the overidding of mk files since I did not get as much warning as kumajaya's sources

**Comment by zwliew** [comment]
It is normal.

**Comment by nick37332001** [comment]
What about this type of errors?
host C++: third_party_protobuf_protobuf_full_do_not_use_arm_host_gyp_32 <= external/chromium_org/third_party/protobuf/src/google/protobuf/message_lite.cc
warning: unknown warning option '-Wno-unused-local-typedef' [-Wunknown-warning-option]
1 warning generated.

**Comment by zwliew** [comment]
Those are normal build warnings in the source.

**Comment by nick37332001** [comment]
Oh lol... I always thought that the toolchain I am currently using is very buggy but nope.

**Comment by nick37332001** [comment]
http://pastebin.com/WqVUNDwv
What about this?

**Comment by zwliew** [comment]
That's a normal warning. Why do you worry so much about build warnings lol

**Comment by balika011** [comment]
I think its because of Eliot :smile:

**Comment by nick37332001** [comment]
cos you know... custom toolchain

**Comment by nick37332001** [comment]
Lol and cos codina wasn't that complicated

**Comment by nick37332001** [comment]
@balika011 I am very paranoid... Thats why I am using paranoid android ( ͡° ͜ʖ ͡°). [Ba, dum, tsss]

**Comment by VIZ-KILLER** [comment]
Selinux in your build is enforcing and in kumajayas build it is permissive. Did that matters?
