### ISSUE TITLE
Camera Bug

### ISSUE THREAD

**Issue by adrianardizza** [zwliew/android_device_xiaomi_hm2014811#96]
I stumbled upon this bug i think after my first reboot of the phone, i rebooted my phone to flash xposed and the camera didn't work after that, i wiped the phone clean and reflashed the rom, even then if i reboot my phone afterwards it will still crash on me.
Steps to Reproduce:
1. Install the ROM (cm12.1 25/09 build)
2. Open the Camera App
3. Reboot
4. It will crash the next time you launch it
Logcat Coming Soon

**Comment by zwliew** [comment]
Please move your logs here: https://github.com/zwliew/android_device_xiaomi_hm2014811/issues/79
