### ISSUE TITLE
Root

### ISSUE THREAD

**Issue by adrianardizza** [zwliew/android_device_xiaomi_hm2014811#97]
Sorry for disturbing you, i know this is very minor but it seems that i can't find the latest build in your list of downloadable builds, sorry for disturbing you :3

**Comment by adrianardizza** [comment]
Woops, and i think i found a bug also (or intentional?), when i installed cm 12.1 it isn't prerooted, so i had to install a SuperSU Package, is cm12.1 supposed to come prerooted or not?

**Comment by zwliew** [comment]
You need to enable root in developer options. The new build will come out by today.

**Comment by adrianardizza** [comment]
Ok, thanks for the clarification, and sorry for disturbing you even though this is a very small issue xD

**Comment by zwliew** [comment]
No problem :p
