### ISSUE TITLE
Kernel Update

### ISSUE THREAD

**Issue by nick37332001** [zwliew/android_device_xiaomi_hm2014811#98]
Is it possible to go to 3.10.89 kernel?
https://github.com/neobuddy89/yu_msm8916

**Comment by zwliew** [comment]
Quite pointless.

**Comment by nick37332001** [comment]
@zwliew why?

**Comment by zwliew** [comment]
Upstreaming the kernel does little to improve things, maybe fixing REALLY minor bugs here and there. 90% of the commits are useless to us and will just clog up the kernel history.

**Comment by nick37332001** [comment]
Oh... @zwliew what about new governors?

**Comment by zwliew** [comment]
I'd rather stick with QCOM's default which is really smooth for us. Other governors are just there for the sake of being there.

**Comment by nick37332001** [comment]
What about mpdecision? Reduce core usage increase batt life.

**Comment by zwliew** [comment]
That is quite arguable without any substantial benchmarks and data so I'll just stick with QCOM's ultra smooth implementation for Lollipop.

**Comment by nick37332001** [comment]
@zwliew for some reason there is lag when closing apps in recent apps. I compiled using a custom toolchain (UBERTC) and its a bit smoother but lag still noticeable. Benchmark scores also improve by 200+ compiling with that toolchain.

**Comment by zwliew** [comment]
Toolchains can hardly improve anything. As for closing apps you mean closing all apps at once? That's quite normal.

**Comment by nick37332001** [comment]
No closing apps one by one

**Comment by zwliew** [comment]
Really slight delay, wouldn't really bother about it since I'm not very proficient in the framework and can't help it lol.

**Comment by nick37332001** [comment]
lol... someone told me to disable scroll view in one of the frameworks but too lazy to fork and edit

**Comment by nick37332001** [comment]
@zwliew what's with Smartfren Andromax Q and Yu Yuphoria splitting CAF branches? Very very confusing. Code aurora is so messed & jumbled up

**Comment by VIZ-KILLER** [comment]
SABER

**Comment by nick37332001** [comment]
@VIZ-KILLER huh?

**Comment by VIZ-KILLER** [comment]
SaberMod toolchain

**Comment by nick37332001** [comment]
@VIZ-KILLER UBERTC is better cos not as laggy as sabermod...
