### ISSUE TITLE
Camera Flash Bug

### ISSUE THREAD

**Issue by adrianardizza** [zwliew/android_device_xiaomi_hm2014811#99]
So it's safe to say that the latest build (9/26) is very stable and i decided to use it as my daily ROM, its smoother then the stock MIUI 6/7 (i think ART gave that performance boost), Camera is working fine but flash doesn't seem to work, it's greyed out in the camera app, i will try and post a logcat very soon.

**Comment by adrianardizza** [comment]
unfortunately i can't get a logcat, but i believe the flash is samsung or somethin like that

**Comment by zwliew** [comment]
Flash works fine for me. What directories do you see in /sys/class/leds?

**Comment by adrianardizza** [comment]
Well I think I'm an idiot, the flash WAS working, I accidentally enabled HDR, sorry about this :3, anyways everything is working great, no bugs except the sound bug, again sorry :3
